<?php

namespace app\assets;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * Tailwind CSS v3 + Lucide icons asset bundle.
 *
 * Delivery mode is controlled by the YIIMP_TAILWIND_CDN constant:
 *
 *   true  — Play CDN (development / no build tooling required).
 *            The in-browser JIT compiler scans rendered HTML and generates
 *            only the classes it finds. Not recommended for production.
 *
 *   false — Compiled static file at web/css/tailwind.css (default / production).
 *            Generated by the Dockerfile build step:
 *              npm ci --prefix yiimp2
 *              npm run build --prefix yiimp2
 *            Served with full Yii AssetManager fingerprinting and caching.
 *
 * Lucide icons are loaded from CDN in both modes. Icons are rendered as
 * <i data-lucide="icon-name"></i> and replaced at runtime by lucide.createIcons()
 * called in the tailwind layout file.
 */
class TailwindAsset extends AssetBundle
{
    /** CDN URL for Lucide — used in both delivery modes. */
    private const LUCIDE_CDN = 'https://unpkg.com/lucide@latest/dist/umd/lucide.min.js';

    public function init(): void
    {
        parent::init();

        if (defined('YIIMP_TAILWIND_CDN') && YIIMP_TAILWIND_CDN) {
            // ── CDN / Play CDN mode ───────────────────────────────────────────
            $this->js        = [
                'https://cdn.tailwindcss.com',
                self::LUCIDE_CDN,
            ];
            $this->jsOptions = ['position' => View::POS_HEAD];
        } else {
            // ── Compiled build mode ───────────────────────────────────────────
            $this->basePath  = '@webroot';
            $this->baseUrl   = '@web';
            $this->css       = ['css/tailwind.css'];
            $this->js        = [self::LUCIDE_CDN];
            $this->jsOptions = ['position' => View::POS_END];
        }
    }

    public $depends = [
        'yii\web\YiiAsset',
        'app\assets\ChartAsset',
    ];
}
