services:
  pool-infra-yiimp:
    command:
      - /bin/sh
      - -c
      - |
        sed -i '/^\[program:yiimp-queue-general\]$/,/^\[/ s/^autostart=true/autostart=false/' /etc/supervisor/conf.d/supervisord.conf
        exec /usr/bin/dumb-init -- /usr/bin/supervisord
